version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./vehicles-frontend
    ports:
      - "80:80"
